name: Conda

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
      fail-fast: false
    defaults:
      run:
        # Needed for conda activation
        shell: bash -l {0}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('ci/environment.yml') }}

      # https://github.com/conda-incubator/setup-miniconda
      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ci/environment.yml
          # Required for caching to work
          use-only-tar-bz2: true

      - name: Set conda-bld output folder to make it easier to find artifacts
        id: condablddir
        # On Windows /conda-bld and \\conda-bld work here but fail later
        # c:\\conda-bld seems to work.... for now
        run: |
          if [ ${{ matrix.os }} = windows-latest ]; then
            echo "::set-output name=condabld::c:\\conda-bld"
          else
            echo "::set-output name=condabld::$HOME/conda-bld"
          fi
        shell: bash

      - run: |
          mkdir ${{ steps.condablddir.outputs.condabld }}
          conda config --set conda_build.output_folder ${{ steps.condablddir.outputs.condabld }}

      - name: Build
        run: |
          conda build -c conda-forge recipe
          ls -R "${{ steps.condablddir.outputs.condabld }}"

      - uses: actions/upload-artifact@v2
        with:
          path: "${{ steps.condablddir.outputs.condabld }}/*-64/steampipe-*"
          if-no-files-found: error

  upload:
    needs: build
    # if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/dev'
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    defaults:
      run:
        # Needed for conda activation
        shell: bash -l {0}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('ci/environment.yml') }}

      # https://github.com/conda-incubator/setup-miniconda
      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ci/environment.yml
          # Required for caching to work
          use-only-tar-bz2: true

      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R

      - name: Upload to Anaconda Cloud
        run: |
          anaconda whoami
          LABEL_ARG=
          # if [ "${{ github.ref == 'refs/heads/dev' }}" = "true" ]; then
          #   LABEL_ARG="--label dev"
          # fi
          for f in artifact/*/steampipe*; do
            anaconda upload --user ${ANACONDA_USER} $f ${LABEL_ARG}
          done
        env:
          ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
